dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"

dotenv: .env
networks:
  defaul: development
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: False
    recipient: "0x35Af6B31a61eC9F030849a3953394A69a1f9f9eC"
  rinkeby:
    verify: True
  mainnet-fork:
    eth_usd_data_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331" #'0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  private_key: ${PRIVATE_KEY}
